# Usa la imagen base de Node.js 21
FROM node:21

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json a /app
COPY package*.json ./

# Elimina el archivo yarn si ya existe
RUN rm -f /usr/local/bin/yarn

# Instala las dependencias utilizando Yarn
RUN npm install -g --force yarn 

RUN yarn install

# Copia todos los archivos del proyecto al directorio de trabajo
COPY . .

# Expone el puerto 8080 en el contenedor
EXPOSE 8080

# Comando para ejecutar el servidor de desarrollo
CMD ["yarn", "run", "serve"]
